### ISSUE TITLE
Naber dostum?

### ISSUE THREAD

**Issue by owlfurty** [dnomak/bana-istedigini-sor#1]
nasilsin?

**Comment by dnomak** [comment]
Bana dribbble davetiyesi ilettiğin günden beri herşey yolunda süper gidiyor daha güzel işler yapmak için ilk motivasyon kaynaklarımdan biriydi şimdi flexible.gs'nin hikayesini yazmaya başladım orda senden de bahsedicem :) Sen nasılsın dostum ? @owlfurty

**Comment by owlfurty** [comment]
Cok mutlu olurum. seni sahnede gormek guzel :) umarim motivasyonunu hic kaybetmezsin

**Comment by dnomak** [comment]
teşekkürler me@dnomak.com adresine mail adresini iletebilirmisin ?

**Comment by ercu3458** [comment]
Merhaba hocam, Ben bir şey soracağım, İllere tıkladığında poppup olarak pencere nasıl açabilirim? İl için bilgiler girilcek pencere içlerine.

**Comment by dnomak** [comment]
@ercu3458 başka issue üzerinden sorsan daha iyi olurdu aslında :) Fancybox http://fancyapps.com/fancybox/ veya Codepen üzerinde hazırladığım Pure CSS Modal Box'ı http://codepen.io/dnomak/pen/pJWYaG inceleyebilirsin. İlerleyen zamanlarda yapılması olası tüm durumları anlatan bir videoda hazırlayacağım SVG Türkiye Haritası için. Youtube kanalınada abone olabilirsin :) https://youtube.com/dogukanguvennomak

**Comment by ercu3458** [comment]
Kanalına abone oluyorum şimdi ve takibin deyim hocam :) ama sorum tam olarak şuydu, ben popup pencere sormadım hocam ile tıklandığında nasıl açarım popupu, bende zaten şuan bir popup var ama il id sine göre nasıl açarım? Saygılar...

**Comment by dnomak** [comment]
<svg> tagi içinde bulunan <g> tagini herhangi bir <div> veya <a> tagi olarak düşünebilirsin ve sendeki popup'ın kullanım şekline göre her ilin <g> tagine kendi kullanım yöntemine göre eklemeler yaparak popup'ın çalışmasını sağlıyabilirsin.

**Comment by ercu3458** [comment]
Hocam sağ olasın yaptım siz cevap  verene kadar. Zaten yaptığım sizin cevapla aynı şekildi. İlginiz için teşekkürler.

**Comment by dnomak** [comment]
halletmene sevindim görüşmek üzere :)
