### ISSUE TITLE
Rocket Npm Start Sorunu

### ISSUE THREAD

**Issue by oguzhanabali** [dnomak/bana-istedigini-sor#10]
Merhabalar sizin rocket'i indirdim. http://flexible.gs'in detaylarını incelemek istedim kullanmak istedim fakat ne yaptıysam npm start komutunu çalıştıramadım. Windows_NT2323 err! diye bir hata alıyorum sürekli tüm paketleri kurdum build ettim ama olmuyor bir türlü yardımcı olurmusun?

**Comment by dnomak** [comment]
geç yanıtım için kusura bakma lütfen gözden kaçmış :( bu durum node versiyonuyla ilgilidir tahminim ama yazdığın hataya net bir şey söylemem mümkün değil nvm kullanırsan node versiyonları arasında kolayca geçiş yaparak bu tarz durumların önüne geçebilirsin.
