### ISSUE TITLE
PSD To Html Yaparken CSS ve Js için Modüler hale getirmek

### ISSUE THREAD

**Issue by mgundogdu38** [dnomak/bana-istedigini-sor#11]
Şimdi bir Psd dosyam var. Bunun html ve css çevrimi çok kötüydü. Ben derdini anlatacak kadar css js bilen biriyim. Şimdi yeniden bootstrap ve flexbox.gs kullanarak tekrar kodlamak istiyorum. Burada kafamı karıştıran şey yaptığım herşeyi tek bir dosyada tutmak istemiyorum. biraz granülize olsun istiyorum. Bunun için yapısal bir teknoloji tavsiyeniz var mı? Sass vs. LESS vs. Stylus kullanmam bu sorunumu çözermi yoksa webpack vs mi kullanmam lazım. Projede tek developer benim. Fullstack gibi. O yüzden çok büyük olmayacak ama doğru olacak frontent çözümünü merak ediyorum. 
6 tane sayfa var diyelim. istiyorum ki o sayfada kullanmadığım bir css orada olmasın.

**Comment by dnomak** [comment]
bunun için gulp kullanabilirsin aslında ben öyle yapıyorum css klasör yapım şu şekilde https://github.com/flexiblegs/website/tree/master/scss gulp için kullandığım tasklerde şu şekilde https://github.com/flexiblegs/website/blob/master/gulpfile.js gulp'ı biraz araştırırsan sorularına gereken yanıtları bulabilirsin yine aklına takılan şeyler olursa yaz lütfen :)

**Comment by mgundogdu38** [comment]
Gulp kullanmayı öğrendim. css/js minify ve bundle için güzel.  scss ile parça parça yapıp ihtiyaçları include edip  dersem best practise oluyor yani. Anladım.  Güzel örnek baya iyi oldu..

**Comment by dnomak** [comment]
süper çok sevindim :)
