### ISSUE TITLE
Tasarımcı Sohbetleri Hakkında

### ISSUE THREAD

**Issue by cagdaskara** [dnomak/bana-istedigini-sor#12]
**Doğukan** merhaba.

Ben İstanbul'da Doğan Holding bünyesinde çalışan ara yüz Tasarımcısı olarak çalışmaktayım. Yıllardır gerek çalıştığım firmalarda gerekse karınca kararınca çok çeşitli projenin içerisinde yer aldım. Çok uzun süredir de dost meclislerinde kendi aramızda **_ya bizim sektördeki insanlarla güzel sohbetler yapsak bunları Youtube üzerinden henüz mezun olmamış ya da yeni mezun öğrencilere ulaştırsak nasıl olur_** şeklinde tartışıyorduk. Akabinde bu konuşmalar biraz daha ayakları yere basar şekle girdiğinde bu sohbet konseptini bizden başkası yapmamıştır gafletinde bulunarak internette biraz araştırmaya başladım. **Ve 1 ay kadar önce** senin kanalını ve bizim yapmak istediğimize çok yakın olan tasarımcı sohbetleri konseptini yaratmış, geliştirmiş ve de çok efektif biçimde kullandığını gördüm. Biraz üzüldüm tabi biraz da kıskandım seni. : ) 

Şimdi tam bu nokta da geçen gün yayınladığın ve kendine zaman ayırmak istediğin için videolara bir süre ara vereceğini anlattığın videoyu izleyince biraz cesaret alarak san bu mesajı atıyorum. Doğukan ben seninkinden biraz farklı ama aynı temellere dayanan **tasarımcı sohbetleri (sektör sohbetleri)** temalı videolar yayınlayacağım bir **Youtube projesi** yapmak istiyorum ve amacım özellikle bizim sektöre okullardaki hocalarının kısıtlı vizyonlarından bakmak durumunda kalan lise ve üniversite öğrencilerine yönelik biraz tanıcı biraz da yön verici içerikler oluşturmak. 

Fakat önümde senin gibi bu işi mükemmele çok yakın biçimde yapan bir örnek olduğu için konuyu önce sana açmak istedim. Bunu icazet almak gibi de düşünebilirsin aslında. Eğer sen de uygun görürsen ben kendi çapımda bu projeye başlamak istiyorum. Eğer gerekli görürsen videoların altında belki **senin imzanın geçeceği belki senden ilham alındığına dair bir yazının** bulunduğu bir ip ucu ile videolarımı hazırlamak istiyorum. **Bu konudaki düşüncelerin nelerdir, bu duruma olumlu yaklaşır mısın ya da ne kadarına ne kadar olumlu yaklaşmaktasın? : )** 

**Acelemin olmadığını belirterek müsait olduğun bir zaman diliminde cevabını bekliyor olacağım.** 

Şimdiden teşekkür ederim. İyi çalışmalar.

**Comment by dnomak** [comment]
Çağdaş Merhaba,

Keşke daha önceden konuşsaydık benim yapıp yapmamam size kesinlikle engel olmamalı ben her türlü şekilde sizi desteklerim mutluluk duyarım sonuç olarak bir karşılık beklemeden insanlara faydalı olabilecek içerikler üretmeye çalışıyoruz hatta sizin kanalı destekleyici videolar ile kanalda toplamış olduğum kitleyi sizden haberdar edebilirimde ayrıca sormak danışmak istediğin teknik detaylarda olursa her zaman sonuna kadar desteklerim :)

Görüşmek üzere, Sevgilerimle.

**Comment by cagdaskara** [comment]
Doğukan tekrar merhaba.

Hızlı geri dönüşün ve özellikle olumlu yaklaşımın beni çok mutlu etti. Teknik süreçteki hazırlık ve karşılaşılaşılabileceğini öngördüğüm sorunları yavaş yavaş aşacağıma inanıyorum. Esas hedefim ve ilk etapta yakalamak istediğim algı ise senin videolarındaki samimi duruşun -ki sanırım sebebi özünde de öyle biri olman- ve motive edici içten tavrını esas alıp aynı kalitede bir şeyler yaratmaya çalışmak olacak.  O vakit ben ilk elden hazırlıkları tamamlayıp süreçten seni de haberdar etmeyi çok isterim. 

_Görüşmek dileğiyle, iyi çalışmalar._

**Comment by dnomak** [comment]
tamamdır haberlerini bekliyorum o zaman me@dnomak.com adresine mailde atabilirsin telefonumu yazıyım sana :)
