### ISSUE TITLE
Yeni bir dil

### ISSUE THREAD

**Issue by kaganulupinar** [dnomak/bana-istedigini-sor#13]
Hocam iyi akşamlar muhtemelen bu soruyu videolarında cevaplamış olabilirsin  ama ben henüz göremedim. Daha yeni yeni keşfettim seni. Şu zamana kadar C# ve C++ dillerinde çokta anlamlı olmayan sadece kendimi oyaladığım projeler yaptım ve şuanda Python dili ile baya içli dışlıyım. Çok fazla yol kat ettiğimi söyleyemem ama yine hoşuma gittiği için zevk alarak çalışıyorum.Yazılım mantığını az çok kavradığımı düşünüyorum tabiki daha çok eksiğim olduğunun da farkındayım. Sizce verdiğim emek ve zaman mantıklı mı yoksa başta bir dile mi yönelmeliyim? 2 3 yıl sonra bu dilin işlevi bitebilir mi? Yada şu daha mantıklı bir soru olabilir sizce gelecek vaat eden emeğimin karşılığını alabileceğim dil hangisi?

**Comment by dnomak** [comment]
Harcadığın emekler kesinlikle karşılıksız kalmaz hiçbir önemi yok dilin aslında yaptığın projeler üzerinden kazanacağın tecrübeler ileride farklı diller kullanmaya başladığında farklı açılardan bakmanı sağlayacaktır. Python hakkında çok detaylı şekilde bilgi sahibi değilim ama genel olarak Türkiye'de bir çok firmada kullanılan bir dil.

**Comment by kaganulupinar** [comment]
Cevabınız için çok teşekkür ederim başarılar.
