### ISSUE TITLE
Github

### ISSUE THREAD

**Issue by mertceyhan** [dnomak/bana-istedigini-sor#14]
Doğukan abi merhaba, geliştirici sohbetlerini severek izliyor ve takip ediyorum. Son paylaştığın videoda bir şey dikkatimi çekti, geliştirici sohbetlerine katılan tüm geliştiriciler Github'ı sıklıkla kullanıyor. Ama bu işe yeni başlayanlar Github'ı kullanmakta zorlanıyor (en azından benim için öyleydi) ne ne değildir anlamakta güçlük çekiyor. Github hakkında ufak bir video çekebilir misin nedir nasıl kullanılır tarzında. Yararlı olacağını düşünüyorum. Teşekkür ederim.

**Comment by dnomak** [comment]
süper öneri teşekkür ederim kısa zamanda yapalım bir video :) cc @f

**Comment by mertceyhan** [comment]
İlgin için ben teşekkür ederim Doğukan abi. Merakla bekliyorum görüşmek üzere.

**Comment by sedattcom** [comment]
Videoyu bende bekliyorum :)
