### ISSUE TITLE
Bir öğrenciden rica

### ISSUE THREAD

**Issue by yyusufaslan** [dnomak/bana-istedigini-sor#15]
​İyi günler, ben Sakarya Üniversitesi Bilgisayar Müh. öğrencisiyim okulumuz da öğrencilerin çalıştığı Toyota'nın Proje Ofisi var. Oraya girmek için bir projeyi yapmam gerek. Benim için gerçekten çok önemli. Proje de kullandığım teknolojiler şunlar ;
Maven tabanlı.
Server: Jetty Maven Plugin
Database: Mysql
Business Layer: Spring, Spring Security, Apache CXF
Persistence Layer: JPA & Hibernate

 Projenin source kodlarını yazdım fakat ayağa kaldıramadım, konfigürasyon dosyalarında mı yoksa server ayarlarında mı hata yapıyorum bilmiyorum.
 Bu proje benim için gerçekten çok önemli sizin yardım edebileceğinizi düşündüm. Biliyorum frontend ile uğraşıyorsunuz fakat düşündüm ki belki bana yardım edecek bu konularda uzman birisine yönlendirebilirsiniz. Belki öğrencinin yapması gereken bir projeyi sorması doğru değil ama bu proje okuldan bağımsız eğer yaparsam Toyota da işe gireceğim, inanın çok minnettar kalırım. Eğer bana yardım edecek birisi olursa hemen İstanbula gelebilirim. Şimdiden Teşekkürler.

**Comment by dnomak** [comment]
eğer bunu senin yerine başka birisi yaparsa toyota ya onun girmesi lazım dolayısıyla bunu senin başarman gerekiyor ismini gerçirdiğin teknolojilere çok yakın değilim çevremde de çok yakın insanlar yok dolayısıyla kademe kademe bu işin nasıl olması gerektiğini araştırıp gerekten takıldığın bir kısımda bu işle uğraşan kişilere ufak sorular ile yine bu sistemi senin ayağa kaldırıyor olman lazım aksi durumda çok anlamlı olmuyor zaten bence bunu halledebilecek güçtesin halletiğin zaman buraya tekrar yaz lütfen :)

**Comment by yyusufaslan** [comment]
düşene birde sen vur abi :) şaka bir yana abi 4 gündür gece gündüz uğraşıyorum inan bilgisayar 4 gündür kapatmadı. Sormamın doğru olmadığı biliyorum da delirecek seviyeye gelmesem sormayacaktım :)
