### ISSUE TITLE
programlama ile ilgili yardim

### ISSUE THREAD

**Issue by BLACK1998** [dnomak/bana-istedigini-sor#16]
Azerbaycandan selamlar. Yardimci olursaniz sevinirim.  Sizin kanali yeni buldum. bakin simdi,ben universitede okuyorum ve bize C++ ve C# dersleri oyretildi,ama cok az oyretildi. ben simdi bilmiyorum programlamanin hangi bolumunu tercih edeyim. sizce WEB DEVELOPER mi, yoksa java falanimi tercih edeyim. cevap verirseniz cok sevinirim.

**Comment by 3r51n** [comment]
+1

**Comment by dnomak** [comment]
@BLACK1998 @3r51n bu tamamen senin hangi kısımla uğraşmaktan daha çok hoşlandığınla ilgili bir durum aslında yani bunun cevabını kendin veriyor olman lazım.

**Comment by BLACK1998** [comment]
tamam.tesekkur ederim. programlama ile ilgili kaynaklariniz varmi?

**Comment by 3r51n** [comment]
@BLACK1998 Www.google.com  ⌨️

**Comment by BLACK1998** [comment]
Ben başka  iyi anlatılan site falan kast etmişdim. Neyse tamam kendim hallederim. 😕
