### ISSUE TITLE
Flexible Grid Sistem gutter veremiyorum

### ISSUE THREAD

**Issue by ukeskin** [dnomak/bana-istedigini-sor#19]
`<div class="wrap xl-gutter-8">
  <div style="background-color:blue;" class="col xl-1-3">01</div>
  <div style="background-color:yellow;" class="col xl-1-3">02</div>
  <div style="background-color:red;" class="col xl-1-3 ">03</div>
[</div>

![f207e72ec6c14341a4a391ffd4c24095](https://cloud.githubusercontent.com/assets/26279663/25784165/a55a216a-3371-11e7-8b44-191f9258297a.png)

`

**Comment by ukeskin** [comment]
<div class="wrap xl-gutter-8">
  <div style="background-color:blue;" class="col xl-1-3">01</div>
  <div style="background-color:yellow;" class="col xl-1-3">02</div>
  <div style="background-color:red;" class="col xl-1-3 ">03</div>
</div>

**Comment by ukeskin** [comment]
`<div class="wrap xl-gutter-8">
  <div style="background-color:blue;" class="col xl-1-3">01</div>
  <div style="background-color:yellow;" class="col xl-1-3">02</div>
  <div style="background-color:red;" class="col xl-1-3 ">03</div>
</div>
`

**Comment by ukeskin** [comment]
html kodları yazıyorum direk çıktı veriyor githubda 
![screenshot_4](https://cloud.githubusercontent.com/assets/26279663/25784297/f2c613c2-3372-11e7-948e-6fc33c15f1f0.png)

**Comment by dnomak** [comment]
haklısın bu durumda gutter göremezsin col içerisine yeni bir div atıp background color'ı bu div'e vermeyi denemelisin. wrap ve col'a dışarıdan css özelliği eklememek lazım yada oluşacak bu tarz durumları iyi biliyor olmak lazım bu aşamada bende ciddi dökümantasyon eksikliği var tabi bunlarla ilgili eğitim videoları çekmeyi planlıyorum :)

**Comment by dnomak** [comment]
umut şimdi avatarına bakınca yaş olarak oldukça küçük olduğunu görüyorum istanbuldaysan bir ektiklik yada organizasyonda mutlaka tanışalım hatta video bile yapabiliriz :)

**Comment by ukeskin** [comment]
Tabiki :) olur. 1 Hazirandan itibaren İstanbul'dayım pek video çekmek taraftarı değilim ama sizinle tanışmayı çok isterim. :) bu arada 2001liyim.
