### ISSUE TITLE
Yeni Geliştirici Sohbetleri

### ISSUE THREAD

**Issue by ozaydinb** [dnomak/bana-istedigini-sor#2]
Selamlar,
youtube kanalını yakından takip ediyorum. İsmen tanıdığım veya hiç tanımadığım geliştiriciler ile yaptığın sobhbetleri izlemek gerçekten çok keyifli oluyor. Hatta alanım olmamasına rağmen tasarımcı sohbetlerini de takip ediyorum. Röportaj yaptığın kişilerin deneyimleri, kullandıkları uygulamaları paylaşmaları gerçekten güzel bir paylaşım oluyor bizim camia için. 

Yalnız dikkatimi çeken kısım genelde linux veya mac os x üzerinde development yapan kişileri dahil ediyorsun sohbetlerine ya da genellikle metglobal'den birilerini görüyorum kanalında, farklı firmalardan insanlarla iletişime geçmeyi düşünüyor musun? (genelde tanıdıklarınla röportaj yapıyorsun sanırım, yani hiç tanımadığın insanlarla da röportaj yapmayı düşünüyor musun?)

**Comment by dnomak** [comment]
@ozaydinb aslında biraz yorulduğum için önümüzdeki 2 bölümde metglobal'den olucak ciddi bir emek istediği için epey yorucu oluyor :) şöyle bir listem var aslında tanıdığım tanımadığım bir çok insanla iletişime geçiyorum :) https://trello.com/b/RKJXe2Sv/planned-videos

**Comment by dnomak** [comment]
@ozaydinb projenin sürekli olucağını düşünürsek çeşitli firmalar ve farklı alanlarda çalışan geliştirici ve tasarımcı arkadaşlarıda göreceğiz :)

**Comment by ozaydinb** [comment]
Tahmin edebiliyorum, çok emek ve zaman isteyen bir işe girişmişsin :) liste kabarıkmış, o zaman video'ların devamını bekliyoruz dört gözle :)

**Comment by dnomak** [comment]
teşekkürler :)
