### ISSUE TITLE
Flexible grid ve Frontend Hk.

### ISSUE THREAD

**Issue by ozkansabanci** [dnomak/bana-istedigini-sor#20]
Merhaba Doğukan,

Öncelikle seni hiç tanımadan isminle hitap etme nedenimin Youtube kanalındaki samimi sohbetler ve paylaşımların olduğunu söyleyeyim. **Umarım bana kızmazsın.** Türk geliştiricileri ile yapmış olduğun videolar inanılmaz keyifli ve benim yıllarca kendi kabuğumda merak ettiğim şeylerdi. Kendimi tanıtmadan konuya girdim kusura bakma. Ben yaklaşık 12 yıldır çalışma hayatında yer alan ancak çok istememe rağmen bir türlü profesyonel anlamda geliştirici olamayan ancak Excel VBA ile kendimi tatmin etmeye çalışan biriyim.
(Örnek için buraya bakabilirsin : [https://youtu.be/7weUEZG8lEI](url)
Özel bir şirkette mali kontrol ve raporlama işleri yapıyorum. 

Neyse konuya geleyim artık :)

Sayende az çok fikir ve bilgi sahibi olduğum web geliştirici alanında bir şeyler öğrenmek istiyorum. Hatta videolardan sonra karar verdim ki bende Front end tarafına yönelmeliyim. Angular.js ve react.js ile ilgili araştırmalar yaparken senin Flexible grid sistemi fark  ettim. (anneciğinin videosunda geçiyordu ilk orada fark ettim sanırım)
Flexible için nasıl destek alabilirim. Front end developer olmak için nereden başlamalıyım. (html, css bunları da iyi bilmiyorum bu arada)

Cevap verirsen sevinirim.

Saygı ve sevgilerimle.

Özkan Sabancı

**Comment by dnomak** [comment]
@ozkansabanci merhaba geç geri dönüşüm için kusura bakma lütfen issue'yu kapatınca üzüldüm ve hemen yanıt yazmak istedim. Flexible Grid System ile ilgili takıldığın bütün soruları bana sorabilirsin. Ayrıca şu videoyu izlemeni tavsiye ediyorum https://youtu.be/-hGM8y8WutM

**Comment by dnomak** [comment]
bu arada güzel yorumların için çok teşekkür ederim çok mutlu oldum :)

**Comment by ozkansabanci** [comment]
Ben hiç cevap vermeyeceksin diye düşünmüştüm :) Bende çok mutlu oldum. **issue** yi burada gereksiz gördüğüm için kapattım. Belirttiğin videoyu daha önce izledim.(kanaldaki tüm videoları izledim galiba) İlgimi bundan dolayı daha çok çekti. O zaman biraz uğraşayım. Yapamazsam yazarım buradan.
Kolay gelsin.

**Comment by dnomak** [comment]
tamamdır haber bekliyorum senden :)
