### ISSUE TITLE
Opensource Project

### ISSUE THREAD

**Issue by MuhEmreKacmaz** [dnomak/bana-istedigini-sor#21]
Merhabalar.
Zaten şuanda çalıştığım bir yer var.Bunun dışında opensource projelerde nasıl yer alabilirim?Böyle yerlere nasıl ulaşabilirim?

İlginize teşekkür ederim.

**Comment by dnomak** [comment]
kendinden ve yaptığın işlerden bahsedersen incelemen için sana open source proje linkleri iletebilirim aslında :) javascript ile uğraşıyorsan lodash'i incelemen oldukça faydalı olabilir https://github.com/lodash/lodash
