### ISSUE TITLE
Android- Service'de api'den çektiğim datayı kullanamıyorum.

### ISSUE THREAD

**Issue by Spbly** [dnomak/bana-istedigini-sor#22]
Merhabalar, Öncelikle seninle Youtube'dan tanıştım abi. Ve Videolarından da senden ve arkadaşlarında da çok memnunum. Sayenizde yazılıma doğru kaymaya karar verdim :)  İzmir ekonomi üni. Bilgisayar müh. 3. sınıf öğrencisiyim. Mobile application dersi için yaptığım projem bu. 2 ay öncesine kadar javaya ve android studio'ya dair fikrim yoktu(Okulda C,Cpp öğrendik).  

Sorunum burda mevcut bi incelersen çok sevinirim. Bilgi eksiğimden dolayı devam edemiyorum. Methodlar classlar artık herşey birbirine girmeye başladı. En azından notification atmak için ... yapmalısın bile çok iş görür. 
http://stackoverflow.com/questions/43959383/does-intentservice-needs-another-parser

**Comment by dnomak** [comment]
güzel yorumların için çok teşekkür ederim ama android hakkında çok bilgi sahibi değilim ve sana yardımcı olabilmem pek mümkün değil ama takım arkadaşım @erdemolkun'un zamanı olursa yanıtlar diye düşünüyorum :)
