### ISSUE TITLE
OpenSource Project

### ISSUE THREAD

**Issue by MuhEmreKacmaz** [dnomak/bana-istedigini-sor#23]
İsmim Emre kaçmaz boş zamanlarımda opensource projelerde yer almak istiyorum.
Şuan çalıştığım şirkette asp.net kullanmaktayız.Akademik bilgi sistemleri proje takip süreçleri üzerine çalışmaktayım.

İlginize teşekkür ederim.

**Comment by dnomak** [comment]
Microsoft'un open source projelerine göz gezdirip kod okuması yapabilirsin .net teknolojilerine ilgi duyuyorsan :) https://github.com/microsoft
