### ISSUE TITLE
E-postalara ulaşamıyorum

### ISSUE THREAD

**Issue by makifcay** [dnomak/bana-istedigini-sor#25]
Merhaba abi, seni uzun süredir takip ediyorum, e posta hesabına birkaç soru atmıştım ama cevap alamadım. Geliştirici sohbeti yaptığın Fatih Acet abiye de ulaşamadım. Genelde blogların iletişim bölümündeki formlar ve kendi domaini olan e postalardan bir türlü cevap alamıyorum. Bunları kuranlar kurduktan sonra bakmayı unutuyor galiba :) 

Bir de en son iTunes'te gelişitirici sohbetlerini mp3 olarak yüklediğini gördüm, bunun için hangi hosting'i kullanıyorsun, bir yazılım/eklenti otomatikman mı hallediyor yoksa sen mp3'e çevirip kendin mi atıyorsun merak ettim.

**Comment by dnomak** [comment]
Merhaba,

Email, youtube, facebook, whatsapp, instagram, twitter ve linkedin üzerinden bir çok mesaj geliyor hepsini yanıtlıyorum ama yanıtlamam biraz zaman alıyor açıkçası kusura bakma.

iTunes için https://www.spreaker.com
