### ISSUE TITLE
SVG Türkiye Haritasına İl İsimlerini Nasıl Ekleyebilirim?

### ISSUE THREAD

**Issue by batuhantozun** [dnomak/bana-istedigini-sor#4]
Selam, SVG Türkiye Haritasına her path için il isimlerini nasıl yazdırabilirim? textPath kullanmaya çalıştım yazdıramadım. Bu konu hakkında yardımcı olabilir misiniz?

**Comment by dnomak** [comment]
bunu kısa zamanda hazırlamam mümkün değil ama küçük bölgelerin içerisine nasıl sığdırabiliriz ? teknik olarak çok mümkün olmayan bir durum gibi geldi bana ?

**Comment by batuhantozun** [comment]
Çok ufak bir yazı fontuyla yazılabilir. Aşağıdaki linkte paylaştığım gibi. Sanırım tek tek x ve y koordinatlarıyla yerleştirmek gerekiyor. SVG pathinin merkezine yerleştirecek bir özellik bulamadım 2 gündür.

Link: http://d-maps.com/carte.php?num_car=25323&lang=en

**Comment by dnomak** [comment]
yakın zamanda bununla ilgili geliştirme yapamadığım ve yapamayacağım için issue'yu kapatıyorum :(

**Comment by abdullahcode** [comment]
Merhabalar, öncelikle bu tür bir çalışmayı bizlerle paylaştığınız için çok teşekkürler. Ben de bu sorunla alaklı bir çözüm arıyorum, kullanılan font ve yazı boyutuyla bu sorunun önüne geçilebilir diye düşünüyorum ama yazıyı nasıl path veya polygon'nun içinde gösterebiliriz,

**Comment by abdullahcode** [comment]
<text transform="matrix(1 0 0 1 386.6471 367.3531)" class="class">İstanbul</text>

Bu eşkilde eklenebiliyor fakat anlamadığım nokta inanılmaz derece performans kaybına yol açıyor, başka bir yolu var mıdır ?
