### ISSUE TITLE
Rocket Master Kurulum'da Hatalar

### ISSUE THREAD

**Issue by KmlYLDZ** [dnomak/bana-istedigini-sor#5]
<img src='https://s18.postimg.org/4q6gq98kp/rocket_master.jpg' border='0' alt='rocket-master'/>

Merhaba
bu repoyu kurarken bu tarz hatalar alıyorum bir fikriniz varmı?

İşletim sistemim "Windows 10"

**Comment by dnomak** [comment]
npm bower ve gulp global'de kurulumu ?

**Comment by dnomak** [comment]
örneğin npm install -g bower şeklinde yüklemelisin öncesinde

**Comment by KmlYLDZ** [comment]
Malesef yine aynı hatayı alıyorum. Acaba node ve npm sürümleri ile alakalı mı? Yoksa Windows'un deliliğinden mi kaynaklanıyor :)

**Comment by dnomak** [comment]
açık soruları kontrol ederken bunu yanıtsız bıraktığımı gördüm kusura bakma lütfen :( umarım sıkıntını halledebilmişsindir ama öneri olarak nvm kullanırsan node versiyonlarını kontrol etmenden kaynaklı bu tarz sıkıntıları ortadan kaldırabilirsin.
