### ISSUE TITLE
turkey svg haritası

### ISSUE THREAD

**Issue by suattii** [dnomak/bana-istedigini-sor#6]
Merhaba,

Paylaşmış olduğunuz türkiye hartiasında istediğim illere logo işareti koymak istiyorum,ve il üzerine geldiğimde var ise bilgi göstermek istiyrum buna benzer bir yapı habertürk sitesindeki haritada mevcut bu konuda yardımcı olabilirmisiniz.

**Comment by dnomak** [comment]
habertürk üzerindeki linki paylaşırmısın bir inceleme yapıyım ?

**Comment by suattii** [comment]
Anasayfa aşağıda yerel haberler başlığın altındaki harita burada sadece üstüne gelince bilgi veriyor ben hem o şeklini hemde istedim illere logo koymak istiyorum.

**Comment by dnomak** [comment]
ne gibi bir ihtiyaçtan logo koymak istiyorsun bu tasarımsal olarak ciddi anlamda sıkıntılı bir durum koyulmaz değil tabiki ama baya uğraşmak gerek :(

**Comment by dnomak** [comment]
birde kilis'e nasıl bir logo koyulabilir koyulsa gözükür mü ?

**Comment by dnomak** [comment]
bu istek müşteri yada çalıştığın kişiden geldiyse bunu ona anlatarak ikna yoluna gitmen çok daha mantıklı gibi geliyor :)

**Comment by suattii** [comment]
iş yaptığım firma türkiyenin hangi illerinde iş yaptığını göstermek için böyle bir talepte bulundu normalde bunu google map ile çok rahat yaptım fakat google map istemediler.

**Comment by suattii** [comment]
dedim fakat ikna edemedim.

**Comment by dnomak** [comment]
anladım dediğim gibi işte bu baya sıkıntılı bir iş bu noktada teknik olarak bu işin doğru yolunu onlara tekrar anlatman gerekiyor veya örnek iste yani bu şekilde bir kullanım var mı yada çizilmiş bir tasarım falan ?

**Comment by suattii** [comment]
http://cbnerede.tccb.gov.tr/ burdan yola çıkarak google mapte yaptım fakat şimdi sizin dediğinizi düşünerekten normal image logo atmak pek mantıklı değil ve zor bişi ama üstüne gelince bilgi amaçlı kutu açılıyorsa logoda atılabilir die düşünüyorum ama sorun şuki nasıl oldunu bilmiyorum. :)

**Comment by dnomak** [comment]
nasıl birşey hayal ediliyor tam olarak bir tasarım varsa atsana bana her ilde farklı logo mu çıkıcak nasıl bişey ben css'le halledebilirim gibi geliyor.

**Comment by suattii** [comment]
Tasarım yok dediğiniz doğru her ilde aynı logo çıkacak tabi istediğim illere ekleme yapabilicem örnek olarak istanbulda iş yapmışım istanbulun üzerinde logo olacak istanbulun üzerine gelince orda yaptığım işleri listeleyen habertürkteki gibi bir alan açılıcak

**Comment by dnomak** [comment]
yakın zamanda bununla ilgili geliştirme yapamadığım ve yapamayacağım için issue'yu kapatıyorum :(
