### ISSUE TITLE
flexible.gs ve material

### ISSUE THREAD

**Issue by serdartaylan** [dnomak/bana-istedigini-sor#7]
Merhaba tamda yeni bir projeye başlıyor ve bootstrap in yetmediğini görüyor iken flexible.gs ile tanışmak iyi oldu. Çalışmaların için teşekkürler şimdiden

flexible.gs i material tasarımla kullanmak istiyorum bu konuda diğer yardımcı material css framework hangisi olmalı tavsiyelerin nelerdir?

İyi çalışmalar.

**Comment by dnomak** [comment]
güzel yorumların için çok teşekkür ederim :) React için http://www.material-ui.com Angular için https://material.angularjs.org tavsiye edebilirim ikisinide kullanmıyorsanız en popüler ve düzgün css frameworklerden biride şudur http://materializecss.com

**Comment by serdartaylan** [comment]
mevcutta şu an için materializecss.com ile ilerliyordum ancak grid yapısı yetersiz kalıyordu.
o zaman ben grid için flexible.gs, material için materializecss.com ile ilerleyim.
(yeni nesil js fw yok jquery ilerliyorum).

bu arada materializecss dün ingilizce idi bugün türkçe eklenmiş. :)

ilginiz için teşekkürler.

**Comment by dnomak** [comment]
ben teşekkür ederim flexible.gs de yetersiz kalan durumlar olursa yazın lütfen yeni özellik bile çıkarız :)
