### ISSUE TITLE
Geliştirici Olmak

### ISSUE THREAD

**Issue by eturkoglu** [dnomak/bana-istedigini-sor#8]
İyi günler abicim ben amatör olarak yazılım geliştiriyorum kendimi profesyonel şekilde nasıl geliştirebilirim yada nasıl bir yol izlemeliyim.

**Comment by emrekeskinmac** [comment]
ne tür yazılımlar geliştiriyorsun hangi konuda ilerlemek istediğin belirtirsen bizde sana yardımcı olabiliriz

**Comment by dnomak** [comment]
teşekkürler @emrekeskinmac kusura bakma @eturkoglu gözden kaçmış bu issue Emre haklı aslında biraz daha detay yazabilirsen süper olur :)
