### ISSUE TITLE
Svg harita üzerinde il isimleri

### ISSUE THREAD

**Issue by zokanzi** [dnomak/bana-istedigini-sor#9]
Selamlar; haritayı çok güzel bir hale getirmişsiniz. Tebrikler. Ancak çok uğraşıp yapamadığım bir durum var. İllerin görünür halde olması. Yani il isimlerinin üzerine gelince değil de, varsayılan olarak görünür olması. Acaba kolay bir şey midir veya sizi çok uğraştırır mı bilmiyorum. Ama yardımcı olabilirseniz çok sevinirim. Kolay gelsin...

**Comment by dnomak** [comment]
çok karmaşıl bir görüntüye yol açar bu durum daha önce böyle bir kullanım gördünüz mü bir yerde buda ilin isminin çıktığı alan konumlandırmasını mouse'a göre yapıyoruz istediğini yaptığımızda ortada kötü bir görüntü oluşturabilir bu istek çalıştığınız birinden geliyorsa bu işlemin doğru olmayacağını ona anlatmanız çok daha iyi olur ama düşündüğün tarzda bir örnek varsa bana iletirsen bakalım tekrar.

**Comment by zokanzi** [comment]
Aynen dediğiniz gibi karmaşık olduğunu söyledim müşterime ve her ildeki bayi sayısının şehrin içinde görünmesine ve tıkladığımızda o listenin popup olarak açılmasına karar verdik. Her ilin orta nokta koordinaatlarını top-left girerek ayrı ayrı tanımladım ve bu şekilde bayi sayısını yazdırabildim. Yanıtınız için teşekkür ederim. Kolay gelsin...
